
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

FunFact.destroy_all 
Region.destroy_all 
Country.destroy_all

FunFact.reset_pk_sequence
Region.reset_pk_sequence
Country.reset_pk_sequence

africa = Region.create(name: "Africa", geo_fact: "Based on the seven-continent model, Africa has the most countries with 54.")
europe = Region.create(name:"Europe", geo_fact: "Europe has the second most countries with 49.")
asia = Region.create(name: "Asia", geo_fact: "Asia has 48 countries, but shares five countries with Europe: share five countries: Azerbaijan, Georgia, Kazakhstan, Russia, and Turkey.")
north_america = Region.create(name: "North America", geo_fact: "North America has the third most contries with 23.")
south_america = Region.create(name: "South America", geo_fact: "South America consist of 12 countries.")
oceaciana = Region.create(name: "Oceania", geo_fact: "Oceania has 14 sovereign states, many of which are part of the British Commonwealth.")


Country.create(name: "Algeria", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AG-flag.jpg", region_id: 1)
Country.create(name: "Angola", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AO-flag.jpg", region_id: 1)
Country.create(name: "Benin", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BN-flag.jpg", region_id: 1)
Country.create(name: "Botswana", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BC-flag.jpg", region_id: 1)
Country.create(name: "Burkina Faso", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/UV-flag.jpg", region_id: 1)
Country.create(name: "Burundi", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BY-flag.jpg", region_id: 1)
Country.create(name: "Cabo Verde", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CV-flag.jpg", region_id: 1)
Country.create(name: "Cameroon", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CM-flag.jpg", region_id: 1)
Country.create(name: "Central African Republic", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CT-flag.jpg", region_id: 1)
Country.create(name: "Chad", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CD-flag.jpg", region_id: 1)
Country.create(name: "Comoros", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CN-flag.jpg", region_id: 1)
Country.create(name: "Democratic Republic of the Congo", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CG-flag.jpg", region_id: 1)
Country.create(name: "Cote d Ivoire", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IV-flag.jpg", region_id: 1)
Country.create(name: "Djibouti", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/DJ-flag.jpg", region_id: 1)
Country.create(name: "Egypt", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/EG-flag.jpg", region_id: 1)
Country.create(name: "Equatorial Guinea", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/EK-flag.jpg", region_id: 1)
Country.create(name: "Eritrea", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ER-flag.jpg", region_id: 1)
Country.create(name: "Eswatini", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/WZ-flag.jpg", region_id: 1)
Country.create(name: "Ethiopia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ET-flag.jpg", region_id: 1)
Country.create(name: "Gabon", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GB-flag.jpg", region_id: 1)
Country.create(name: "Gambia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GA-flag.jpg", region_id: 1)
Country.create(name: "Ghana", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GH-flag.jpg", region_id: 1)
Country.create(name: "Guinea", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GV-flag.jpg", region_id: 1)
Country.create(name: "Guinea-Bissau", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PU-flag.jpg", region_id: 1)
Country.create(name: "Kenya", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KE-flag.jpg", region_id: 1)
Country.create(name: "Lesotho", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LT-flag.jpg", region_id: 1) 
Country.create(name: "Liberia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LI-flag.jpg", region_id: 1)
Country.create(name: "Libya", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LY-flag.jpg", region_id: 1)
Country.create(name: "Madagascar", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MA-flag.jpg", region_id: 1)
Country.create(name: "Malawi", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MI-flag.jpg", region_id: 1)
Country.create(name: "Mali", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ML-flag.jpg", region_id: 1)
Country.create(name: "Mauritania", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MR-flag.jpg", region_id: 1)
Country.create(name: "Mauritius", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MP-flag.jpg", region_id: 1)
Country.create(name: "Morocco", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MO-flag.jpg", region_id: 1)
Country.create(name: "Mozambique", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MZ-flag.jpg", region_id: 1)
Country.create(name: "Namibia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/WA-flag.jpg", region_id: 1)
Country.create(name: "Niger", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NG-flag.jpg", region_id: 1)
Country.create(name: "Nigeria", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NI-flag.jpg", region_id: 1)
Country.create(name: "Rwanda", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/RW-flag.jpg", region_id: 1)
Country.create(name: "Sao Tome and Principe", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TP-flag.jpg", region_id: 1)
Country.create(name: "Senegal", flag:  "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SG-flag.jpg", region_id: 1)
Country.create(name: "Seychelles", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SE-flag.jpg", region_id: 1)
Country.create(name: "Sierra Leone", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SL-flag.jpg", region_id: 1)
Country.create(name: "Somalia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SO-flag.jpg", region_id: 1)
Country.create(name: "South Africa", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SF-flag.jpg", region_id: 1)
Country.create(name: "South Sudan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/OD-flag.jpg", region_id: 1)
Country.create(name: "Sudan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SU-flag.jpg", region_id: 1)
Country.create(name: "Tanzania", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TZ-flag.jpg", region_id: 1)
Country.create(name: "Togo", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TO-flag.jpg", region_id: 1)
Country.create(name: "Tunisia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TS-flag.jpg", region_id: 1)
Country.create(name: "Uganda", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/UG-flag.jpg", region_id: 1)
Country.create(name: "Zambia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ZA-flag.jpg", region_id: 1)
Country.create(name: "Zimbabwe", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ZI-flag.jpg", region_id: 1)

Country.create(name: "Albania", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AL-flag.jpg", region_id: 2)
Country.create(name: "Andorra", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AN-flag.jpg", region_id: 2)
Country.create(name: "Austria", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AU-flag.jpg", region_id: 2)
Country.create(name: "Azerbaijan",flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AJ-flag.jpg", region_id: 2)
Country.create(name: "Belarus", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BO-flag.jpg", region_id: 2)
Country.create(name: "Belgium", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BE-flag.jpg", region_id: 2)
Country.create(name: "Bosnia and Herzegovina", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BK-flag.jpg", region_id: 2)
Country.create(name: "Bulgaria", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BU-flag.jpg", region_id: 2)
Country.create(name: "Croatia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/HR-flag.jpg", region_id: 2)
Country.create(name: "Czech Republic", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/EZ-flag.jpg", region_id: 2)
Country.create(name: "Denmark", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/DA-flag.jpg", region_id: 2)
Country.create(name: "Estonia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/EN-flag.jpg", region_id: 2)
Country.create(name: "Finland", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/FI-flag.jpg", region_id: 2)
Country.create(name: "France", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/FR-flag.jpg", region_id: 2)
Country.create(name: "Georgia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GG-flag.jpg", region_id: 2)
Country.create(name: "Germany", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GM-flag.jpg", region_id: 2)
Country.create(name: "Greece", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GR-flag.jpg", region_id: 2)
Country.create(name: "Vatican City", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/VT-flag.jpg", region_id: 2)
Country.create(name: "Hungary", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/HU-flag.jpg", region_id: 2)
Country.create(name: "Iceland", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IC-flag.jpg", region_id: 2)
Country.create(name: "Ireland", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/EI-flag.jpg", region_id: 2)
Country.create(name: "Italy", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IT-flag.jpg", region_id: 2)
Country.create(name: "Kazakhstan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KZ-flag.jpg", region_id: 2)
Country.create(name: "Kosovo", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KV-flag.jpg", region_id: 2)
Country.create(name: "Latvia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LG-flag.jpg", region_id: 2)
Country.create(name: "Liechtenstein", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LS-flag.jpg", region_id: 2)
Country.create(name: "Lithuania", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LH-flag.jpg", region_id: 2)
Country.create(name: "Luxembourg", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LU-flag.jpg", region_id: 2)
Country.create(name: "Malta", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MT-flag.jpg", region_id: 2)
Country.create(name: "Moldova", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MD-flag.jpg", region_id: 2)
Country.create(name: "Monaco", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MN-flag.jpg", region_id: 2)
Country.create(name: "Montenegro", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MJ-flag.jpg", region_id: 2)
Country.create(name: "Netherlands", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NL-flag.jpg", region_id: 2)
Country.create(name: "North Macedonia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MK-flag.jpg", region_id: 2)
Country.create(name: "Norway", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NO-flag.jpg", region_id: 2)
Country.create(name: "Poland", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PL-flag.jpg", region_id: 2)
Country.create(name: "Portugal", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PO-flag.jpg", region_id: 2)
Country.create(name: "Russia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/RS-flag.jpg", region_id: 2)
Country.create(name: "San Marino", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SM-flag.jpg", region_id: 2)
Country.create(name: "Serbia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/RI-flag.jpg", region_id: 2)
Country.create(name: "Slovakia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LO-flag.jpg", region_id: 2)
Country.create(name: "Slovenia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SI-flag.jpg", region_id: 2)
Country.create(name: "Spain", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SP-flag.jpg", region_id: 2)
Country.create(name: "Sweden", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SW-flag.jpg", region_id: 2)
Country.create(name: "Switzerland", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SZ-flag.jpg", region_id: 2)
Country.create(name: "Turkey", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TU-flag.jpg", region_id: 2)
Country.create(name: "Ukraine", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/UP-flag.jpg", region_id: 2)
Country.create(name: "United Kingdom", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/UK-flag.jpg", region_id: 2)

Country.create(name: "Afghanistan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AF-flag.jpg", region_id: 3)
Country.create(name: "Armenia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AM-flag.jpg", region_id: 3)
Country.create(name: "Bahrain", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BA-flag.jpg", region_id: 3)
Country.create(name: "Bangladesh", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BG-flag.jpg", region_id: 3)
Country.create(name: "Bhutan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BT-flag.jpg", region_id: 3)
Country.create(name: "Brunei", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BX-flag.jpg", region_id: 3)
Country.create(name: "Burma", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BM-flag.jpg", region_id: 3)
Country.create(name: "Cambodia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CB-flag.jpg", region_id: 3)
Country.create(name: "China", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CH-flag.jpg", region_id: 3)
Country.create(name: "Cyprus", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CY-flag.jpg", region_id: 3)

Country.create(name: "India", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IN-flag.jpg", region_id: 3)
Country.create(name: "Indonesia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ID-flag.jpg", region_id: 3)
Country.create(name: "Iran", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IR-flag.jpg", region_id: 3)
Country.create(name: "Iraq", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IZ-flag.jpg", region_id: 3)
Country.create(name: "Israel", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/IS-flag.jpg", region_id: 3)
Country.create(name: "Japan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/JA-flag.jpg", region_id: 3)
Country.create(name: "Jordan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/JO-flag.jpg", region_id: 3)

Country.create(name: "North Korea",flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KN-flag.jpg", region_id: 3)
Country.create(name: "South Korea", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KS-flag.jpg", region_id: 3)
Country.create(name: "Kuwait", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KU-flag.jpg", region_id: 3)
Country.create(name: "Kyrgyzstan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KG-flag.jpg", region_id: 3)
Country.create(name: "Laos", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LA-flag.jpg", region_id: 3)
Country.create(name: "Lebanon", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/LE-flag.jpg", region_id: 3)
Country.create(name: "Malaysia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MY-flag.jpg", region_id: 3)
Country.create(name: "Maldives", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MV-flag.jpg", region_id: 3)
Country.create(name: "Mongolia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MG-flag.jpg", region_id: 3)
Country.create(name: "Nepal", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NP-flag.jpg", region_id: 3)
Country.create(name: "Oman", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MU-flag.jpg", region_id: 3)
Country.create(name: "Pakistan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PK-flag.jpg", region_id: 3)
Country.create(name: "Philippines", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/RP-flag.jpg", region_id: 3)
Country.create(name: "Qatar", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/QA-flag.jpg", region_id: 3)
Country.create(name: "Saudi Arabia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SA-flag.jpg", region_id: 3)
Country.create(name: "Singapore", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SN-flag.jpg", region_id: 3)
Country.create(name: "Sri Lanka", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CE-flag.jpg", region_id: 3)
Country.create(name: "Syria", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SY-flag.jpg", region_id: 3)
Country.create(name: "Tajikistan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TI-flag.jpg", region_id: 3)
Country.create(name: "Thailand", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TH-flag.jpg", region_id: 3)
Country.create(name: "Timor-Leste", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TT-flag.jpg", region_id: 3)

Country.create(name: "Turkmenistan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TX-flag.jpg", region_id: 3)
Country.create(name: "United Arab Emirates", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AE-flag.jpg", region_id: 3)
Country.create(name: "Uzbekistan", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/UZ-flag.jpg", region_id: 3)
Country.create(name: "Vietnam", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/VM-flag.jpg", region_id: 3)
Country.create(name: "Yemen", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/YM-flag.jpg", region_id: 3)

Country.create(name: "Antigua and Barbuda", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AC-flag.jpg", region_id: 4)
Country.create(name: "Bahamas", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BF-flag.jpg", region_id: 4)
Country.create(name: "Barbados", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BB-flag.jpg", region_id: 4)
Country.create(name: "Belize", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BH-flag.jpg", region_id: 4)
Country.create(name: "Canada", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CA-flag.jpg", region_id: 4)
Country.create(name: "Costa Rica", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CS-flag.jpg", region_id: 4)
Country.create(name: "Cuba", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CU-flag.jpg", region_id: 4)
Country.create(name: "Dominica", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/DO-flag.jpg", region_id: 4)
Country.create(name: "Dominican Republic", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/DR-flag.jpg", region_id: 4)
Country.create(name: "El Salvador", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ES-flag.jpg", region_id: 4)
Country.create(name: "Grenada", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GJ-flag.jpg", region_id: 4)
Country.create(name: "Guatemala", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GT-flag.jpg", region_id: 4)
Country.create(name: "Haiti", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/HA-flag.jpg", region_id: 4)
Country.create(name: "Honduras", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/HO-flag.jpg", region_id: 4)
Country.create(name: "Jamaica", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/JM-flag.jpg", region_id: 4)
Country.create(name: "Mexico", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/MX-flag.jpg", region_id: 4)
Country.create(name: "Nicaragua", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NU-flag.jpg", region_id: 4)
Country.create(name: "Panama", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PM-flag.jpg", region_id: 4)
Country.create(name: "Saint Kitts and Nevis", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/SC-flag.jpg", region_id: 4)
Country.create(name: "Saint Lucia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/ST-flag.jpg", region_id: 4)
Country.create(name: "Saint Vincent and the Grenadines", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/VC-flag.jpg", region_id: 4)
Country.create(name: "United States", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/US-flag.jpg", region_id: 4)


Country.create(name: "Australia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AS-flag.jpg", region_id: 6)
Country.create(name: "Fiji", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/FJ-flag.jpg", region_id: 6)
Country.create(name: "Kiribati", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/KR-flag.jpg", region_id: 6)
Country.create(name: "Marshall Islands", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/RM-flag.jpg", region_id: 6)
Country.create(name: "Federated States of Micronesia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/FM-flag.jpg", region_id: 6)
Country.create(name: "Nauru", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NR-flag.jpg", region_id: 6)
Country.create(name: "New Zealand", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NZ-flag.jpg", region_id: 6)
Country.create(name: "Palau", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PS-flag.jpg", region_id: 6)
Country.create(name: "Papua New Guinea", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PP-flag.jpg", region_id: 6)
Country.create(name: "Samoa", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/WS-flag.jpg", region_id: 6)
Country.create(name: "Solomon Islands", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BP-flag.jpg", region_id: 6)
Country.create(name: "Tonga", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TN-flag.jpg", region_id: 6)
Country.create(name: "Tuvalu", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/TV-flag.jpg", region_id: 6)
Country.create(name: "Vanuatu", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NH-flag.jpg", region_id: 6)

Country.create(name: "Argentina", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/AR-flag.jpg", region_id: 5)
Country.create(name: "Bolivia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BL-flag.jpg", region_id: 5)
Country.create(name: "Brazil", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/BR-flag.jpg", region_id: 5)
Country.create(name: "Chile", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CI-flag.jpg", region_id: 5)
Country.create(name: "Colombia", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/CO-flag.jpg",region_id: 5)
Country.create(name: "Ecuador", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/EC-flag.jpg", region_id: 5)
Country.create(name: "Guyana", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/GY-flag.jpg", region_id: 5)
Country.create(name: "Paraguay", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PA-flag.jpg",region_id: 5)
Country.create(name: "Peru", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/PE-flag.jpg", region_id: 5)
Country.create(name: "Suriname", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/NS-flag.jpg", region_id: 5)
Country.create(name: "Uruguay", flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/UY-flag.jpg", region_id: 5)
Country.create(name: "Venezuela",flag: "https://www.cia.gov/library/publications/resources/the-world-factbook/attachments/flags/VE-flag.jpg", region_id: 5)

algeria = FunFact.create(first: "Algeria is located in North Africa, bordering the Mediterranean Sea, between Morocco and Tunisia.", second: "The flag's colors represent Islam (green), purity and peace (white), and liberty (red).", third: "On July 5, 1962, Algeria achieved independence from France after an eight-year-long war - one of the bloodiest and longest in the whole decolonisation process.", country_id: 1)
vatican_city = FunFact.create(first: "Surrounded by Rome, Italy, Vatican City is the smallest sovereign state in the world by both area (0.44 sq km) and population (825).", second: "The flag of Vatican City consist of two vertical bands yellow (hoist side) and white with the crossed keys of Saint Peter centered in the white band; the yellow color represents the pope's spiritual power, the white his worldly power.", third: " Latin is the offical language of Vatican City.  Even the ATMs even offer Latin as one of the languages for making transactions.", country_id: 71)